#!/bin/bash

# source surfraw config
source $HOME/.config/surfraw/conf

# get local config
if [[ -f $HOME/.config/rofi-surfraw/config ]]; then
    source $HOME/.config/rofi-surfraw/config
fi

query=""

# get list of search engines from surfraw
if [[ $@ == *"--no-list"* ]]; then
    elvis=$(ls ~/.config/surfraw/elvi)
else
#    elvis=$(sr -elvi | awk '{ print "?"$1 }' | tail -n +2)
    elvis=$(sr -elvi | awk '{if (NR!=1) print $1 }')
fi

# append_history () {
#   echo $* >> ~/.surfraw-history
#   cat ~/.surfraw-history | uniq | tail -n 100 > ~/.surfraw-history.next
#   mv ~/.surfraw-history.next ~/.surfraw-history
# }

get_query () {
  query=$(rofi -dmenu -p "Search: " -lines 0)

  if [[ $query == "" ]]; then exit
  else
    :
    # append_history $query
  fi
}

main () {
  get_query $*

# Draw Menu
  ELVI_MSG="Search for <b>"${query}"</b>"
  ROFI_CMD=''
  elvi=$(echo -e "${default}\n${elvis}" | rofi -dmenu -i -no-custom -auto-select -mesg "${ELVI_MSG}" -p "Search: ")

  # Some logic
  if [[ $elvi == "" ]]; then
    main $query
  else
    sr ${elvi} ${query}
  fi
}

if [[ $1 == "--help" ]]; then
    echo "rofi-surfraw - (C) 2015 Rasmus Steinke <rasi at xssn dot at>"
    echo "---"
    echo "--help         this help"
    echo "--no-list      do not show inbuild search engines"
    echo "--no-custom    do not show custom search engines"
else
    main ""
fi
