#!/usr/bin/env bash
# Sends a dunstify notification with information from mpc -f.
# Adapted from https://bbs.archlinux.org/viewtopic.php?pid=684807#p684807

ALBUM_ART="$(mktemp).png"
ALBUM_ART_WIDTH="125"

FMT_TITLE="[%title%]|[%file%]"
FMT_ARTIST="[%artist%]"

mpc_format() {
  args=("$@")
  mpc -f "${args[0]}" current
}

title="$(mpc_format "$FMT_TITLE")"
artist="$(mpc_format "$FMT_ARTIST")"

# Summary/artist can't start w/ -
title="${title/#-/−}"
artist="${artist/#-/−}"

art_src=$(mpc-art)

notify-send "${title}" ${artist} \
  -a "ncmpcpp" \
  -i "{art_src}"
