#!/usr/bin/env bash
# Sends a dunstify notification with information from mpc -f.
# Adapted from https://bbs.archlinux.org/viewtopic.php?pid=684807#p684807

ALBUM_ART="$(mktemp).png"
ALBUM_ART_WIDTH="125"

FMT_TITLE="[%title%]|[%file%]"
FMT_ARTIST="[%artist%]"

mpc_format() {
  args=("$@")
  mpc -f "${args[0]}" current
}

# Get album art
# ffmpeg -y -i "${XDG_MUSIC_DIR%%/}/$(mpc current --format '%file%')" \
#   "$ALBUM_ART" 2>/dev/null &&\
#   mogrify -resize "$ALBUM_ART_WIDTH" "$ALBUM_ART"
#
# # Get the dunstify id
# [ ! -z "$(cat "$DUNSTIFY_ID")" ] && id_arg="-r $(cat "$DUNSTIFY_ID")"

title="$(mpc_format "$FMT_TITLE")"
artist="$(mpc_format "$FMT_ARTIST")"

# Summary/artist can't start w/ -
title="${title/#-/−}"
artist="${artist/#-/−}"

echo $title

notify-send "${title}" ${artist}
  -a "ncmpcpp" \
  -i "/tmp/album-art.png"
  # -p $id_arg > "$DUNSTIFY_ID" \
  # "$title" "$artist"
